name = "ChunkSplitters"
uuid = "ae650224-84b6-46f8-82ea-d812ca08434e"
authors = ["Leandro Martinez <lmartine@unicamp.br> and contributors"]
version = "2.4.6-DEV"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"

[extras]
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"

[compat]
OffsetArrays = "1"
julia = "1.6"
Documenter = "1"
Compat = "4.12"
Test = "1.6"
TestItemRunner = "0.2"
TestItems = "0.1, 1"
Aqua = "0.8"
BenchmarkTools = "1"

[targets]
test = ["Test", "TestItemRunner", "OffsetArrays", "Aqua", "Documenter", "BenchmarkTools"]
